---
- import_playbook: bootstrap.yml
- import_playbook: add-config-files.yml
- import_playbook: contributor-keys.yml
- import_playbook: install-docker.yml

- import_playbook: init-ldbc-interactive.yml
- import_playbook: init-ldbc-datagen.yml
